name: Deploy Storybook
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3
        with:
          persist-credentials: false
      - name: Install and Build 🔧
        run: | # Install npm packages and build the Storybook files
          cd packages/ui
          npm install
          npm run build
          cd ../../storybook
          npm install
          npm run build-storybook