name: Build and Deploy Storybook

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - master

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Install dependencies and build 🔧
        run: |
          cd packages/ui
          npm install
          npm run build
          cd ../../storybook
          npm install
          npm run build-storybook

      - name: Deploy 🚀
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: storybook
          folder: storybook/storybook-static
          clean: true
          target-folder: docs
